# Generated by Django 2.0.7 on 2018-07-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180703_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bulma_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
