# Generated by Django 2.0.7 on 2018-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_bulma_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='length',
            field=models.CharField(default='5 minute', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
